name: product_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  image_picker: ^0.8.5+3
flutter:
  uses-material-design: true
