// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2q35zDd3a4xude7z3eL4I_lYFHrqCaSg',
    appId: '1:479321530434:web:39d9c641a9db2c1b37cddb',
    messagingSenderId: '479321530434',
    projectId: 'productapp-72d2f',
    authDomain: 'productapp-72d2f.firebaseapp.com',
    storageBucket: 'productapp-72d2f.firebasestorage.app',
    measurementId: 'G-WQES09Q9G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKsVDrqrhFxc3FSrZOQSyOX_UJpIp7iak',
    appId: '1:479321530434:android:f8b44100428c801a37cddb',
    messagingSenderId: '479321530434',
    projectId: 'productapp-72d2f',
    storageBucket: 'productapp-72d2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_IzEaPR4-zqmkD_SzYZaAt4ysR-Ftcg',
    appId: '1:479321530434:ios:b13b28fe32d698b037cddb',
    messagingSenderId: '479321530434',
    projectId: 'productapp-72d2f',
    storageBucket: 'productapp-72d2f.firebasestorage.app',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0_IzEaPR4-zqmkD_SzYZaAt4ysR-Ftcg',
    appId: '1:479321530434:ios:b13b28fe32d698b037cddb',
    messagingSenderId: '479321530434',
    projectId: 'productapp-72d2f',
    storageBucket: 'productapp-72d2f.firebasestorage.app',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2q35zDd3a4xude7z3eL4I_lYFHrqCaSg',
    appId: '1:479321530434:web:3aa7b14850c955ca37cddb',
    messagingSenderId: '479321530434',
    projectId: 'productapp-72d2f',
    authDomain: 'productapp-72d2f.firebaseapp.com',
    storageBucket: 'productapp-72d2f.firebasestorage.app',
    measurementId: 'G-CNJ3E1YGM0',
  );
}
